import type { Event } from './types';

export const events: Event[] = [
  {
    id: '1',
    title: 'AI in Modern Web Development',
    description: 'A deep dive into how AI is shaping the future of web development, from code generation to user experience.',
    date: '2025-11-28',
    time: '5:00 PM',
    location: 'Lecture Hall A',
    category: 'Workshop',
    image: {
      id: 'event-workshop',
      url: 'https://picsum.photos/seed/1/600/400',
      alt: 'Students collaborating during a workshop.',
      hint: 'workshop students',
    },
  },
  {
    id: '2',
    title: 'The Future of Sustainable Tech',
    description: 'Join industry experts to discuss green computing and sustainable innovations in technology.',
    date: '2025-12-05',
    time: '2:00 PM - 4:00 PM',
    location: 'Main Auditorium',
    category: 'Seminar',
    image: {
      id: 'event-seminar',
      url: 'https://picsum.photos/seed/2/600/400',
      alt: 'A speaker presenting at a seminar.',
      hint: 'conference speaker',
    },
  },
  {
    id: '3',
    title: 'Campus Beats Music Festival',
    description: 'An evening of live music from student bands and local artists. Food, fun, and great vibes!',
    date: '2025-12-12',
    time: '6:00 PM onwards',
    location: 'Central Quad',
    category: 'Festival',
    image: {
      id: 'event-music-festival',
      url: 'https://picsum.photos/seed/3/600/400',
      alt: 'A lively outdoor music festival on campus.',
      hint: 'music festival',
    },
  },
  {
    id: '4',
    title: 'Innovate & Create Hackathon',
    description: 'A 24-hour coding challenge to build innovative solutions for real-world problems. Prizes to be won!',
    date: '2025-12-18',
    time: 'Starts at 9:00 AM',
    location: 'Tech Hub, Building C',
    category: 'Hackathon',
    image: {
      id: 'event-tech-hackathon',
      url: 'https://picsum.photos/seed/5/600/400',
      alt: 'Students coding at a hackathon.',
      hint: 'hackathon coding',
    },
  },
    {
    id: '5',
    title: 'Annual University Sports Day',
    description: 'Compete in various track and field events and cheer for your friends. A day of sportsmanship and fun.',
    date: '2026-01-25',
    time: 'All Day',
    location: 'University Sports Complex',
    category: 'Sports',
    image: {
      id: 'event-sports-day',
      url: 'https://picsum.photos/seed/6/600/400',
      alt: 'Students participating in a race on sports day.',
      hint: 'running race',
    },
  },
  {
    id: '6',
    title: 'Startup Career Fair 2026',
    description: 'Connect with exciting startups and explore internship and full-time opportunities in the tech industry.',
    date: '2026-02-02',
    time: '11:00 AM - 5:00 PM',
    location: 'Exhibition Hall',
    category: 'Career',
    image: {
      id: 'event-career-fair',
      url: 'https://picsum.photos/seed/7/600/400',
      alt: 'Students talking to recruiters at a career fair.',
      hint: 'career fair',
    },
  },
];
